//vis_driver_g.c

/****************** Include Files ********************/
//include "xparameters.h"

//begin edit Maximilian Hafeneder

#include "vis_driver.h"
#include "vis_driver_i.h"


/************************** Constant Definitions ***************************/
//shared constant defintions should be done in at_driver.h

/**************************** Type Definitions *****************************/

/************************** Variable Definitions ***************************/

//this fragment can be also automatically generated by Xilinx Vitis,
//however in this case here adapt it manually if there are changes in the HW platform

//##INSERT YOUR CODE HERE 
//TOCO CHECK baseadress, interrupts and interrupt-parent
VIS_Config VIS_ConfigTable[] __attribute__ ((section (".drvcfg_sec"))) = {
	{
		"xlnx,vis-1.0.0", /* compatible */
		0x10000, /* reg */ //baseaddress of VIS IP
		0x5f5e100, /* clock-frequency */ 
               //100MHz = 100e6 (hex value)
		0x4001, /* interrupts */ //interruptid and interrupt properties  
            //bits[11:0] interrupt-id; bits[15:12] trigger type and level flags (interrupt 1 (counting starts starts with 0))
            //bits[15:12] trigger type and level flags;  (Trigger type is 0x4 = active high level-sensitive)
              //1 = low-to-high edge triggered; 2 = high-to-low edge triggered; 
              //4 = active high level-sensitive; 8 = active low level-sensitive
            //bits[19:16] CPU Mask (which CPU -> in our case 0)
            //bit[20] interrupt-type (1: PPI (Per Processor Interrupt), 0: SPI (Shared Processor Interrupt)  (Interrupt-type is 0 = SPI )
		0x41200001 /* interrupt-parent */ // baseaddress of the interrupt controller (the lowest bit is ignored)
            //lowesest bit is the intctype (XGet_IntcType); for the GIC it is 0 for the AXI INTC it is 1 (-> 1 in our case)
//end edit Maximilian Hafeneder
    },
	 {
		 NULL
	}
};
//##INSERT YOUR CODE HERE END

/************************** Function Definitions ***************************/
