//at_driver_g.c

/****************** Include Files ********************/
//#include "xparameters.h"

#include "at_driver.h"
#include "at_driver_i.h"


/************************** Constant Definitions ***************************/
//shared constant definitions should be done in at_driver.h

/**************************** Type Definitions *****************************/

/************************** Variable Definitions ***************************/

//this fragment can be also automatically generated by Xilinx Vitis,
//however in this case here adapt it manually if there are changes in the HW platform

//##INSERT YOUR CODE HERE
// TODO: Basisadresse nach BSP-Update pruefen (XPAR_AUDIO_0_BASEADDR)
AT_Config AT_ConfigTable[] __attribute__ ((section (".drvcfg_sec"))) = {
	{
		"xlnx,audio-1.0.0",
		XPAR_AUDIO_0_BASEADDR,
		0x5F5E100,
	},
	{
		NULL
	}
};
//##INSERT YOUR CODE HERE END

/************************** Function Definitions ***************************/
