//aud_driver_g.c

/****************** Include Files ********************/
//#include "xparameters.h"

#include "aud_driver.h"
#include "aud_driver_i.h"


/************************** Constant Definitions ***************************/
//shared constant definitions should be done in aud_driver.h

/**************************** Type Definitions *****************************/

/************************** Variable Definitions ***************************/

//this fragment can be also automatically generated by Xilinx Vitis,
//however in this case here adapt it manually if there are changes in the HW platform

//##INSERT YOUR CODE HERE
// BEGIN NEW Felix Knoll
// TODO: Basisadresse nach BSP-Update pruefen (XPAR_AUDIO_0_BASEADDR)
AUD_Config AUD_ConfigTable[] __attribute__ ((section (".drvcfg_sec"))) = {
	{
		"xlnx,audio-1.0.0",
		0x10000,
		0x5F5E100,
	},
	{
		NULL
	}
};
// END NEW Felix Knoll
//##INSERT YOUR CODE HERE END

/************************** Function Definitions ***************************/
